### ISSUE TITLE
Setting gain parameter

### ISSUE THREAD

**Issue by tcrussell** [rtoenniges/node-red-contrib-hx711#3]
Is it possible to set the gain parameter for HX711? Choices are CHA 128 or 64 and CHB 32. Maybe this could be an input 'msg.gain'.

Thanks,
Tom

**Comment by rtoenniges** [comment]
Added in v1.0.3

Feel free to test it :-)
You can set Gain as 32, 64 or 128.

**Comment by tcrussell** [comment]
Hi Robin

Wow. Thanks, I will give it a try and let you know. Waiting for the
hardware to arrive in a few days.

Tom

**Comment by tcrussell** [comment]
Hi Robin

I tried it but found a couple of problems. On line 8 of hx711.js you
had this.hx_gain = config.hx_scale; I fixed that but I am getting a message
when I run it:
"TypeError: sensor.setGain is not a function"
I took a look at the c code and it sure looks like a valid function call.

Thanks,
Tom

**Comment by rtoenniges** [comment]
Hi Tom,

damn copy paste bug :-)

Please have a look a version 1.0.7

**Comment by tcrussell** [comment]
Hi Robin

That did it!  I tested both 128 and 64.
Thanks for taking care of this so quickly.

Tom

**Comment by tcrussell** [comment]
Hi Robin

I connected a load cell to the SparkFun board and found that sometimes the
reading is doubled (see chart below) which probably indicates that the data
transfer is off by 1 bit. I have not looked at the underlying c++ code but
perhaps interrupts from the Pi are causing the problem. Have you observed
this at all?

Tom

[image: image.png]
